services:
  - type: web
    name: resumizer
    env: docker
    region: ohio
    plan: free
    dockerContext: .
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: resume-rag
      - key: SKIP_INDEX_CHECK
        value: true
